=== patterncoder/infojectiveReports/InfojectiveReportsConsoleTests/Reports/ReportSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ReportSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace ="http://oldtowndining.com/schemas"
           xmlns="http://oldtowndining.com/schemas"
           elementFormDefault="qualified">

  <xs:element name="Report">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Parameters"  >
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Parameter" minOccurs="0"  maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="Name" type="xs:string"></xs:attribute>
                  <xs:attribute name="ParameterType" type="xs:string"></xs:attribute>
                  <xs:attribute name="ValidationText" type="xs:string"></xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Layout">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Margin-Top" default="72"></xs:element>
              <xs:element name="Margin-Bottom" default="36"></xs:element>
              <xs:element name="Margin-Left" default="36"></xs:element>
              <xs:element name="Margin-Right" default="36"></xs:element>
              <xs:element name="Orientation" default="Portrait"></xs:element>
              <xs:element name="Page-Size" default="Letter"></xs:element>
              <xs:element name="PageEvent" default="TwoColumnHeaderFooter"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Head">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name"></xs:element>
              <xs:element name="Title"></xs:element>
              <xs:element name="Description"></xs:element>
              <xs:element name="Connection"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Body">
          <xs:complexType>
            
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              
              <xs:element name="Text" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="SpacingBefore" type="xs:decimal" use="optional" ></xs:attribute>
                      <xs:attribute name="SpacingAfter" type="xs:decimal" use="optional" ></xs:attribute>
                      <xs:attribute name="FontFamily" use="optional">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="times_roman"/>
                            <xs:enumeration value="helvetica"/>
                            <xs:enumeration value="courier"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="FontStyle" use="optional">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="normal"/>
                            <xs:enumeration value="italic"/>
                            <xs:enumeration value="bold"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="FontSize" use="optional">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="8"/>
                            <xs:enumeration value="10"/>
                            <xs:enumeration value="12"/>
                            <xs:enumeration value="14"/>
                            <xs:enumeration value="16"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="FontColor" use="optional">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:enumeration value="black"/>
                            <xs:enumeration value="red"/>
                            <xs:enumeration value="green"/>
                            <xs:enumeration value="blue"/>
                            <xs:enumeration value="grey"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>

              <xs:element name="Image" minOccurs="0" >
                <xs:complexType>
                  <xs:attribute name="Source" type="xs:string"></xs:attribute>
                  <xs:attribute name="PositionX" type="xs:decimal"  use="optional"></xs:attribute>
                  <xs:attribute name="PositionY" type="xs:decimal" use="optional"></xs:attribute>
                  <xs:attribute name="PercentScaleX" type="xs:decimal" use="optional"></xs:attribute>
                  <xs:attribute name="PercentScaleY" type="xs:decimal" use="optional"></xs:attribute>
                </xs:complexType>
              </xs:element>
              
              
              <xs:element name="HTMLSnippet" minOccurs="0" maxOccurs="unbounded">
                
                <xs:complexType>
                  
                  <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="StyleSheet" minOccurs="1">
                      <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                          <xs:element name="ClassStyle">
                            <xs:complexType>
                              <xs:attribute name="ClassName" type="xs:string" use="required"></xs:attribute>
                              <xs:attribute name="Property" type="xs:string" use="required"></xs:attribute>
                              <xs:attribute name="Value" type="xs:string" use="required"></xs:attribute>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="TagStyle" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="TagName" type="xs:string" use="required"></xs:attribute>
                              <xs:attribute name="Property" type="xs:string" use="required"></xs:attribute>
                              <xs:attribute name="Value" type="xs:string" use="required"></xs:attribute>
                        
                            </xs:complexType>
                          </xs:element>
                        </xs:choice>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Elements">
                      <xs:complexType>
                        <xs:choice minOccurs="1" maxOccurs="unbounded">
                                  <xs:element name="Paragraph">
                                  <xs:complexType>
                                    <xs:attribute name="Binding" type="xs:string" use="required"></xs:attribute>
                                    <xs:attribute name="SpacingBefore" type="xs:decimal" use="optional" ></xs:attribute>
                                    <xs:attribute name="SpacingAfter" type="xs:decimal" use="optional" ></xs:attribute>
                                  </xs:complexType>
                            </xs:element>
                                  <xs:element name="Snippet">
                                    <xs:complexType>
                                      <xs:attribute name="Binding" type="xs:string" use="required"></xs:attribute>
                                    </xs:complexType>
                                  </xs:element>
                        </xs:choice>
                      </xs:complexType>
                    </xs:element>
                    
                  </xs:choice>
                  
                  <xs:attribute name="DataSource" type="xs:string"></xs:attribute>
                </xs:complexType>
              </xs:element>
              
              
              <xs:element name="DataTable" minOccurs="0"    >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Row" maxOccurs="unbounded" >
                      <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                          <xs:element name="Cell">
                            <xs:complexType>
                              <xs:attribute name="colSpan" type="xs:string"  ></xs:attribute>
                              <xs:attribute name="borderWidth" type="xs:string" use="optional"></xs:attribute>
                              <xs:attribute name="binding" type="xs:string" use="required"></xs:attribute>
                              <xs:attribute name="Padding" type="xs:string" use="optional"></xs:attribute>
                              <xs:attribute name="Header" type="xs:string" use="optional"></xs:attribute>
                              <xs:attribute name="FontFamily" use="optional">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:enumeration value="times_roman"/>
                                    <xs:enumeration value="helvetica"/>
                                    <xs:enumeration value="courier"/>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="FontStyle" use="optional">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:enumeration value="normal"/>
                                    <xs:enumeration value="italic"/>
                                    <xs:enumeration value="bold"/>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="FontSize" use="optional">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:enumeration value="8"/>
                                    <xs:enumeration value="10"/>
                                    <xs:enumeration value="12"/>
                                    <xs:enumeration value="14"/>
                                    <xs:enumeration value="16"/>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="FontColor" use="optional">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:enumeration value="black"/>
                                    <xs:enumeration value="red"/>
                                    <xs:enumeration value="green"/>
                                    <xs:enumeration value="blue"/>
                                    <xs:enumeration value="grey"/>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="Align"  use="optional">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="left"/>
                                  <xs:enumeration value="right"/>
                                  <xs:enumeration value="center"/>
                                </xs:restriction>
                              </xs:simpleType></xs:attribute>
                              <xs:attribute name="VerticalAlign"  use="optional">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:enumeration value="top"/>
                                    <xs:enumeration value="middle"/>
                                    <xs:enumeration value="bottom"/>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="Border"  use="optional">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:enumeration value="left"/>
                                    <xs:enumeration value="right"/>
                                    <xs:enumeration value="top"/>
                                    <xs:enumeration value="bottom"/>
                                    <xs:enumeration value="box"/>
                                    <xs:enumeration value="none"/>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>

                              
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="DataSource" type="xs:string" use="required" ></xs:attribute>
                  <xs:attribute name="columnCount" type="xs:string" use="required" ></xs:attribute>
                  <xs:attribute name="tableWidth" type="xs:string" use="optional" ></xs:attribute>
                  <xs:attribute name="SpacingBefore" type="xs:decimal" use="optional" ></xs:attribute>
                  <xs:attribute name="SpacingAfter" type="xs:decimal" use="optional" ></xs:attribute>
                  <xs:attribute name="columnWidths" type="xs:string" use="required" ></xs:attribute>
                  <xs:attribute name="tableAlign"  use="optional">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="left"/>
                        <xs:enumeration value="right"/>
                        <xs:enumeration value="center"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
                
              </xs:element>
                
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
 
</xs:schema>

=== patterncoder/infojectiveReports/InfojectiveReportsConsoleTests/Reports/Report3.xml
<?xml version="1.0" encoding="utf-8" ?>
<Report xmlns="http://oldtowndining.com/schemas"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://oldtowndining.com/schemas ReportSchema.xsd" >
  
  <Parameters>
    <Parameter Name="@emp_id" ParameterType="Int" ValidationText="Employee Number"/>
  </Parameters>
  
  <Layout>
    <Margin-Top>96</Margin-Top>
    <Margin-Bottom>72</Margin-Bottom>
    <Margin-Left>36</Margin-Left>
    <Margin-Right>36</Margin-Right>
    <Orientation>Portrait</Orientation>
    <Page-Size>Legal</Page-Size>
  </Layout>
  <Head>
    <Name>Employee Policies</Name>
    <Title>Old Town Dining, LLC</Title>
    <Description>Assinged policies and acknowledgement.</Description>
    <Connection>Data Source=MsSql.oldtowndining.com;Initial Catalog=oldtowndining;User ID=oldtowndining;Password=y5EQJ5m7C3</Connection>
  </Head>
  <Body>
    <Image Source="~/DesktopModules/HayleyReports/Reports/logootd.gif" PercentScaleX="15" PercentScaleY="15" PositionX="30" PositionY="850"/>
    <DataTable datasource="select obj_num, first_name + ' ' + last_name as name from sw.employees where id = @emp_id"
                columnCount="1"
                columnWidths="1"
                tableWidth="200"  tableAlign="right"  SpacingAfter="18">
      <Row>
        <Cell  binding="#{obj_num}" Align="right"  Border="none" FontSize="14" FontStyle="italic"></Cell>
        
      </Row>
      <Row>
        <Cell  binding="{name}"  Align="right" Border="none" FontSize="12" FontStyle="italic"></Cell>

      </Row>
      
    </DataTable>
    <Text> 
      
    </Text>
    <DataTable datasource="select  ep.policy_id, ep.employee_id,
ep.assigned_date, ep.acknowledged,
	p.title
 from sw.employee_policies ep 
 inner join sw.policies p on ep.policy_id = p.id
 where ep.employee_id = @emp_id order by ep.assigned_date, p.title"
                columnCount="3"
                columnWidths="1;1;1"
                tableWidth="540"  tableAlign="right">
      <Row>
        <Cell  binding="{title}" Border="bottom"  ></Cell>
        <Cell binding="{assigned_date}" Align="center"  Border="bottom"></Cell>
        <Cell binding="{acknowledged}" Align="right" Border="bottom" ></Cell>

      </Row>

    </DataTable>
    
    
    
  </Body>
  
</Report>

=== patterncoder/infojectiveReports/InfojectiveReportsConsoleTests/Reports/PolicyReport2.xml
<?xml version="1.0" encoding="utf-8" ?>
<Report xmlns="http://oldtowndining.com/schemas"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://oldtowndining.com/schemas ReportSchema.xsd" >

  <Parameters>
    <Parameter Name="@id" ParameterType="int" ValidationText="Enter the policy id "/>
   
  </Parameters>
  
  <Layout>
    <Margin-Top>96</Margin-Top>
    <Margin-Bottom>72</Margin-Bottom>
    <Margin-Left>36</Margin-Left>
    <Margin-Right>36</Margin-Right>
    <Orientation>Portrait</Orientation>
    <Page-Size>Letter</Page-Size>
    <PageEvent>TwoColumnHeaderFooter</PageEvent>
  </Layout>
  <Head>
    <Name>Single Policy Printing</Name>
    <Title>Old Town Dining, LLC</Title>
    <Description>Individual policies may not convey all pertinent information.</Description>
    <Connection>OTDSiteSqlServer</Connection>
  </Head>
  <Body>

    
    

    <HTMLSnippet DataSource="select id, title, policy_text from sw.policies where id = @id">
      <StyleSheet>
      <TagStyle TagName="p" Property="face" Value="times-roman"/>
      <TagStyle TagName="p" Property="leading" Value="14"/>
      <TagStyle TagName="ul" Property="indent" Value="30"/>
      <TagStyle TagName="li" Property="leading" Value="14"/>
      <TagStyle TagName="li" Property="face" Value="times-roman"/>
      <TagStyle TagName="p" Property="SpacingAfter" Value="10"/>
      <TagStyle TagName="li" Property="SpacingAfter" Value="10"/>
      </StyleSheet>
      <Elements>
        <Paragraph Binding="String {title}"/>
        <Snippet Binding="{policy_text}"/>
      </Elements>
      
    </HTMLSnippet>
    
    
  </Body>
  
</Report>

=== patterncoder/infojectiveReports/InfojectiveReportsConsoleTests/Reports/ReportWithXSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<Report xmlns="http://oldtowndining.com/schemas"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://oldtowndining.com/schemas ReportSchema.xsd" >
  
  <Parameters>
    <Parameter Name="@emp_seq" ParameterType="Int" ValidationText="This needs an int."/>
  </Parameters>
  
  <Layout>
    <Margin-Top>144</Margin-Top>
    <Margin-Bottom>72</Margin-Bottom>
    <Margin-Left>72</Margin-Left>
    <Margin-Right>72</Margin-Right>
    <Orientation>Portrait</Orientation>
    <Page-Size>Letter</Page-Size>
  </Layout>
  <Head>
    <Name>Employee Logins</Name>
    <Title>Employee Logins</Title>
    <Description>Employee logins for these dates.</Description>
    <Connection>Data Source=MsSql.oldtowndining.com;Initial Catalog=oldtowndining;User ID=oldtowndining;Password=y5EQJ5m7C3</Connection>
  </Head>
  <Body>
    <Text>Slerbage</Text>
    <DataTable datasource="select emp_seq, last_name + ', ' + first_name as name, sign_in_code from sw.employees where emp_seq > @emp_seq order by last_name, first_name"
                columnCount="2"
                columnWidths="1;5"
                tableWidth="540">
      <Row>
        <Cell binding="emp_seq" colSpan="1" borderWidth="1"></Cell>
        <Cell binding="name" colSpan="1" borderWidth="1"></Cell>
        
        
        
        
        
      </Row>
      
    </DataTable>
    
    
  </Body>
  
</Report>

=== patterncoder/infojectiveReports/InfojectiveReportsConsoleTests/Reports/ODBCTestReport2.xml
<?xml version="1.0" encoding="utf-8" ?>
<Report xmlns="http://oldtowndining.com/schemas"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://oldtowndining.com/schemas ReportSchema.xsd" >

  <Parameters>
    
   
  </Parameters>
  
  <Layout>
    <Margin-Top>96</Margin-Top>
    <Margin-Bottom>72</Margin-Bottom>
    <Margin-Left>36</Margin-Left>
    <Margin-Right>36</Margin-Right>
    <Orientation>Portrait</Orientation>
    <Page-Size>Letter</Page-Size>
    <PageEvent>TwoColumnHeaderFooter</PageEvent>
  </Layout>
  <Head>
    <Name>Site Users</Name>
    <Title>dnndev_700 Site Users</Title>
    <Description>This grabs the current website users.</Description>
    <Connection>Micros</Connection>
  </Head>
  <Body>


    <DataTable DataSource="select emp_seq, first_name, last_name from micros.emp_def " columnCount="3" columnWidths="1;4;4" >
      <Row>
        <Cell binding="{emp_seq}"/>
        <Cell binding="{first_name}"/>
        <Cell binding="{last_name}"/>
      </Row>
    </DataTable>

    
    
    
  </Body>
  
</Report>

=== patterncoder/infojectiveReports/InfojectiveReportsConsoleTests/Reports/EmpSalesReport.xml
<?xml version="1.0" encoding="utf-8" ?>
<Report xmlns="http://oldtowndining.com/schemas"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://oldtowndining.com/schemas ReportSchema.xsd" >

  <Parameters>
    <Parameter Name="@DateStart" ParameterType="int" ValidationText="YYYYMMDD Format"/>
   
  </Parameters>
  
  <Layout>
    <Margin-Top>96</Margin-Top>
    <Margin-Bottom>72</Margin-Bottom>
    <Margin-Left>36</Margin-Left>
    <Margin-Right>36</Margin-Right>
    <Orientation>Portrait</Orientation>
    <Page-Size>Letter</Page-Size>
    <PageEvent>TwoColumnHeaderFooter</PageEvent>
  </Layout>
  <Head>
    <Name>Server Sales</Name>
    <Title>Server Sales</Title>
    <Description>This is the sales for specified day.</Description>
    <Connection>Micros</Connection>
  </Head>
  <Body>


    <DataTable DataSource="SELECT ed.last_name + ', ' + ed.first_name as name, e.net_sls_ttl, 
               (et.trk_ttl_59 + et.trk_ttl_60 - et.trk_ttl_61 - et.trk_ttl_62) as 'Amount Due',
               et.trk_ttl_47 as 'AR', et.trk_ttl_48 as 'DepositRedeem',
               et.trk_ttl_49 as 'GC Redeem',
               et.trk_ttl_08 as 'CertSold' 
               FROM micros.v_R_employee e inner join micros.v_r_employee_trk et on e.emp_seq = et.emp_seq
               and e.shift_number = et.shift_number inner join micros.emp_def ed on ed.emp_seq = e.emp_seq
               where CONVERT( CHAR(8), e.start_time, 112) = CONVERT( CHAR(8), @DateStart, 112) 
               and  e.net_sls_ttl &lt;&gt; 0 order by ed.obj_num "
               columnCount="7" columnWidths="3;1;1;1;1;1;1" >
      <Row>
        
        <Cell binding="{name}" Header="Name" />
        <Cell binding="{net_sls_ttl}" Header="Sales"/>
        <Cell binding="{Amount Due}" Header="Cash Due"/>
        <Cell binding="{AR}" Header="A/R"/>
        <Cell binding="{DepositRedeem}" Header="Dep. Redeem"/>
        <Cell binding="{GC Redeem}" Header="GC Redeem"/>
        <Cell binding="{CertSold}" Header="Dep/GC Sold"/>
      </Row>
    </DataTable>

    
    
    
  </Body>
  
</Report>
